### ISSUE TITLE
cant get it to run in replit

### ISSUE THREAD

**Issue by divineblade7** [juddisjudd/tzone_tracker#1]
It installed the dependencies listed, but it seems to be hung on a JSON decode error. i tried using the webhook just pasted in as well as using replit's "secret" and neither would work that i could tell
![image](https://github.com/juddisjudd/tzone_tracker/assets/32503738/938ce19b-bfeb-4d47-bd03-992dffa7ae9d)

**Comment by divineblade7** [comment]
somewhat solved. seems to only work if more than 1 webhook is listed.

**Comment by juddisjudd** [comment]
> somewhat solved. seems to only work if more than 1 webhook is listed.

Interesting, I'd have to actually see your json and any other potential changes you made to really tell.
If I had to guess maybe you didn't have a "debug" webhook set and missing a comma or had a comma somewhere.

If you didn't have a debug webhook and you didn't change anything in the main script then yea I can see an error happening since the main script utilizes that, so not really an error with the script, its working as intended.

**Comment by divineblade7** [comment]
Gotcha. If the repo is updated I can try the newest revision as well. Thank for for this. It's is a very helpful program. 

No changes were made. Left initial labels for webhook and just added webhook to debug one and the first one. The second webhook listed I tried a few things. Deleting: it would error, leaving replace me it would work and just say that 2nd webhook was expected to be replaced. Or listed the webhook 2x and the debug own as well would work just post 2x as expected. 

If you send me a friend request on discord I can share if that's alright
